language: node_js

services:
  - docker

node_js:
  - '10'

os:
  - linux

sudo: false

install:
  - npm install

before_script:
  - npm run lint

script:
  - npm run build

after_success:
  - npm run docker-build

deploy:
  provider: script
  script: npm run docker-push
  on:
    branch: master

cache:
  directories:
    - node_modules

git:
  depth: 1

branches:
  only:
    - master